name: deploy-prd
on: [push]  
jobs:
  deploy-prd:
    runs-on: ubuntu-18.04
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
    steps:
      - uses: docker-practice/actions-setup-docker@master
        run: |
          set -x
          docker version
          docker run --rm hello-world
    steps:
      - uses: isbang/compose-action@v1.0.0
        with:
          compose-file: './docker-compose.yml'
          build-flags: '--volumes'
    steps:
      - uses: isbang/compose-action@v1.0.0
        with:
          compose-file: './docker-compose.yml'
          up-flags: '--volumes'
